[versions]
android-gradle-plugin = "8.6.0"
androidx-activity = "1.9.2"
androidx-appcompat = "1.7.0"
androidx-core = "1.13.1"
androidx-documentfile = "1.0.1"
androidx-fragment = "1.8.3"
androidx-preference = "1.2.1"
jgit = "6.10.0.202406032230-r"
json = "20240303"
junit = "1.2.1"
kotlin = "2.0.20"
kudzu = "5.3.0"
material = "1.12.0"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidx-documentfile" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "androidx-preference" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }
kudzu = { group = "io.github.copper-leaf", name = "kudzu-core", version.ref = "kudzu" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Test
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }

# Build script
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }
json = { group = "org.json", name = "json", version.ref = "json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
